# Generated by Django 4.1.1 on 2022-09-18 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=100)),
                ('package_info', models.CharField(max_length=300)),
                ('no_of_people', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('average_pricing', models.CharField(max_length=50)),
                ('no_of_server', models.CharField(max_length=50)),
                ('no_of_dishes', models.CharField(max_length=50)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.business')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Accept', 'Accept'), ('Declined', 'Declined')], max_length=50)),
                ('business_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.business')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
