# Generated by Django 4.1.1 on 2022-09-21 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='rating',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
